config/routes.rb
Curso::Application.routes.draw do

  match 'login'  => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  resources :user_sessions
  resources :users

  match 'signup' => 'users#new', :as => :signup

  resources :courses do
    resources :editions
  end

  root :to => 'courses#index'

end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :description, :name
  validates :name, :presence => true
  has_many :editions, :inverse_of => :course

  scope :filtered, lambda { |f|
    if f.nil?
      where({})
    else
      includes(:editions).where("editions.active = ?", f=='active')
    end
  }
end

app/models/edition.rb
class Edition < ActiveRecord::Base
  belongs_to :course, :inverse_of => :editions
  attr_accessible :active, :finish, :location, :price, :seats, :start

  # Validación personalizada (each)
  validates_each :start do |record, attr, value|
    error_cond = value && value < Date.today && record.active?
    record.errors.add(attr, 'must happen in the future if active') if error_cond
  end

  # validacion con metodo/simbolo
  validate :validate_end_date_before_start_date

  def location_map_link
    location.blank? ? '' : "http://maps.google.es/?q=" + CGI.escape(location)
  end

  def price
    self.price_in_cents.to_i / 100.0
  end

  def price=(val = 0)
    self.price_in_cents= (val.to_f * 100).to_i
  end

private
  def validate_end_date_before_start_date
    if finish && start
      errors.add(:finish, "Put error text here") if finish < start
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :email, :password, :password_confirmation
  acts_as_authentic # incluye comportamiento de athlogic
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

private
  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    @current_user = current_user_session && current_user_session.record
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_filter :check_user, :except => [:show,:index]

  # GET /courses
  # GET /courses.json
  def index
    @filter = params[:filter].blank? ? nil : params[:filter]
    @courses = Course.filtered(params[:filter]).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  def check_user
   if current_user
     true
   else
     redirect_to login_path(:return_to => url_for(action: params[:action]))
   end
  end
end

app/controllers/editions_controller.rb
class EditionsController < ApplicationController
  before_filter :load_course 

  # GET /editions
  # GET /editions.json
  def index
    @editions = @course.editions.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @editions }
    end
  end

  # GET /editions/1
  # GET /editions/1.json
  def show
    @edition = @course.editions.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @edition }
    end
  end

  # GET /editions/new
  # GET /editions/new.json
  def new
    @edition = @course.editions.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @edition }
    end
  end

  # GET /editions/1/edit
  def edit
    @edition = @course.editions.find(params[:id])
  end

  # POST /editions
  # POST /editions.json
  def create
    @edition = @course.editions.new(params[:edition])

    respond_to do |format|
      if @edition.save
        format.html { redirect_to [@course,@edition], notice: 'Edition was successfully created.' }
        format.json { render json: @edition, status: :created, location: @edition }
      else
        format.html { render action: "new" }
        format.json { render json: @edition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /editions/1
  # PUT /editions/1.json
  def update
    @edition = @course.editions.find(params[:id])

    respond_to do |format|
      if @edition.update_attributes(params[:edition])
        format.html { redirect_to [@course,@edition], notice: 'Edition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @edition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /editions/1
  # DELETE /editions/1.json
  def destroy
    @edition = @course.editions.find(params[:id])
    @edition.destroy

    respond_to do |format|
      format.html { redirect_to course_editions_url(@course) }
      format.json { head :no_content }
    end
  end

  private

  def load_course
    @course = Course.find(params[:course_id])
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user_session = UserSession.new
    @return_to = params[:return_to]
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Successfully logged in."
      redirect_to params[:return_to] || root_url
    else
      render :action => 'new'
    end
  end

  def destroy
    @user_session = UserSession.find # find sin nada porque no es un modelo 'normal'
    @user_session.destroy
    flash[:notice] = "Successfully logged out."
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
      @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Registration successful."
      redirect_to root_url
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      flash[:notice] = "Successfully updated profile."
      redirect_to root_url
    else
      render :action => 'edit'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper

  def link_to_editions(course)
    ed_count = course.editions.size
    if ed_count == 0
      link_to("Add",new_course_edition_path(course))
    else
      link_to("View #{ed_count}", course_editions_path(course))
    end
  end

end

app/helpers/editions_helper.rb
module EditionsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>

<%= link_to_unless(@filter.nil?, 'All', courses_path) %>
&nbsp;|&nbsp;
<%= link_to_unless(@filter == 'active', 'Active', courses_path(:filter => 'active')) %>
&nbsp;|&nbsp;
<%= link_to_unless(@filter == 'unactive', 'Unactive', courses_path(:filter => 'unactive')) %>

<table>
<% @courses.each do |course| %>
  <tr>
    <th><%= link_to course.name, course %></th>
    <td><%= course.description %></td>
    <td><%= link_to_editions(course) %></td>
    <% if current_user %>
      <td><%= link_to 'Edit', edit_course_path(course) %></td>
      <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @course.name %>
</p>

<p>
  <b>Description:</b>
  <%= @course.description %>
</p>


<%= link_to 'Editions', course_editions_path(@course) %> |
<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/editions/_form.html.erb
<%= form_for([@course,@edition]) do |f| %>
  <% if @edition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@edition.errors.count, "error") %> prohibited this edition from being saved:</h2>

      <ul>
      <% @edition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start %><br />
    <%= f.date_select :start %>
  </div>
  <div class="field">
    <%= f.label :finish %><br />
    <%= f.date_select :finish %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :seats %><br />
    <%= f.number_field :seats %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price, :value => @edition.price.to_i, :step => 1 %>.00 &euro;
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/editions/edit.html.erb
<h1>Editing <%= @course.name %> edition</h1>

<%= render 'form' %>

<%= link_to 'Show', [@course,@edition] %> |
<%= link_to 'Back', course_editions_path(@course) %>

app/views/editions/index.html.erb
<h1>Listing <%= @course.name%>'s editions</h1>

<table>
  <tr>
    <th>Start</th>
    <th>Finish</th>
    <th>Location</th>
    <th>Active</th>
    <th>Seats</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @editions.each do |edition| %>
  <tr>
    <td><%= edition.start %></td>
    <td><%= edition.finish %></td>
    <td><%= edition.location %></td>
    <td><%= edition.active %></td>
    <td><%= edition.seats %></td>
    <td>
    <%= number_to_currency(edition.price, unit: "&euro;", format: "%n %u") %>
    </td>
    <td><%= link_to 'Show', course_editions_path([@course,edition]) %></td>
    <td><%= link_to 'Edit', [:edit, @course, edition] %></td>
    <td><%= link_to 'Destroy', [@course,edition], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '<< Back', courses_path %>
&nbsp;|&nbsp;
<%= link_to '[+] New Edition', new_course_edition_path(@course) %>

app/views/editions/new.html.erb
<h1>New <%= @course.name %> edition</h1>

<%= render 'form' %>

<%= link_to 'Back', course_editions_path(@course) %>

app/views/editions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Start:</b>
  <%= @edition.start %>
</p>

<p>
  <b>Finish:</b>
  <%= @edition.finish %>
</p>

<p>
  <b>Location:</b>
  <%= ( @edition.location? ? link_to(@edition.location, @edition.location_map_link) : '') %>
</p>

<p>
  <b>Active:</b>
  <%= @edition.active %>
</p>

<p>
  <b>Seats:</b>
  <%= @edition.seats %>
</p>

<p>
  <b>Price in cents:</b>
  <%= @edition.price_in_cents %>
</p>

<p>
  <b>Course:</b>
  <%= @edition.course %>
</p>


<%= link_to 'Edit', edit_course_edition_path(@course,@edition) %> |
<%= link_to 'Back', course_editions_path(@course) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Curso</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="user_nav">
    <% if current_user %>
      <%= link_to_unless_current("Edit profile", edit_user_path(:current)) %>
      &nbsp;|&nbsp;
      <%= link_to("Logout", logout_path) %>
    <% else %>
      <% if controller == 'user_session' %>
        <%= render :partial => "user_sessions/user_session", :object => UserSession.new %>
        &nbsp;|&nbsp;
      <% end %>
      <%= link_to_unless_current("Register", new_user_path) %>
      &nbsp;|&nbsp;
      <%= link_to_unless_current("Log in", login_path) %>
    <% end %>
  </div>

<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

<%= yield %>

</body>
</html>

app/views/user_sessions/_user_session.html.erb
<%= form_for user_session do |f| %>
  <% if user_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_session.errors.count, "error") %> prohibited this course from being saved:</h2>
      <ul>
      <% @user_session.errors.full_messages.each do |msg| %>
        <div class="field"><%= msg %></div>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field actions">
    <%= f.label :username, "Username" %>
    <%= f.text_field :username %>
    <%= f.label :password, "Password" %>
    <%= f.password_field :password %>
    <%= hidden_field_tag :return_to, @return_to %>
    <%= f.submit "Log in" %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Log in</h1>
<%= render @user_session %>

app/views/users/_user.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this course from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <div class="field"><%= msg %></div>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username, "Username" %></br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email, "Email" %></br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password, "Password" %></br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Password confirmation" %></br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1><%= @user.username %>'s profile</h1>
<%= render @user %>

app/views/users/new.html.erb
<h1>New User</h1>
<%= render @user %>